version: '3.7'
services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command: -nginx.scrape-uri=http://localhost:8080/nginx_status
    ports:
      - "9113:9113"
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
